version: 1.0.{build}
environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
configuration:
  - Debug
  - Release
platform:
  - Win32
  - x64
  - ARM64
build:
  project: WinStd.sln
  parallel: true
  verbosity: minimal
